version: "3.8"

services:
  backend:
    image: souleymanevml/pizza-back:latest
    container_name: estiam-pizza-backend
    restart: always
    ports:
      - "8000:8000"
    working_dir: /app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - frontend

  frontend:
    image: souleymanevml/pizza-front:latest
    container_name: estiam-pizza-frontend
    restart: always
    ports:
      - "5173:5173"
    working_dir: /app
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
   