name: CI - Pizza

on:
  pull_request:
    branches: [main, stage, feat/ci]
  push:
    branches: [main, stage, feat/ci]

jobs:
  frontend:
    name: Pizza front
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pizza front Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pizza-front:test -f pizza-front/Dockerfile ./pizza-front

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag & push pizza-front image
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/pizza-front:test \
                      ${{ secrets.DOCKERHUB_USERNAME }}/pizza-front:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pizza-front:latest

  backend:
    name: Pizza backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run backend tests
        run: docker run --rm -v $GITHUB_WORKSPACE/pizza-back/tests:/tests \
             ${{ secrets.DOCKERHUB_USERNAME }}/pizza-back:test \
             pytest /tests -q

      - name: Run backend tests
        run: docker run --rm pizza-back

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag & push back image
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/pizza-back:test \
                     ${{ secrets.DOCKERHUB_USERNAME }}/pizza-back:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pizza-back:latest